### ISSUE TITLE
Text and icon color problem

### ISSUE THREAD

**Issue by aikrom** [bndkt/sharemystack#262]
There is some problem with text and icon color.

![photo_2023-10-08_14-10-38](https://github.com/bndkt/sharemystack/assets/8126925/f222d1ff-cba9-41db-9d89-6f94451ee7b3)
![photo_2023-10-08_14-10-37](https://github.com/bndkt/sharemystack/assets/8126925/180c02b9-9a41-4bc9-974c-3dc4f8b17cec)
![photo_2023-10-08_14-10-35](https://github.com/bndkt/sharemystack/assets/8126925/a980c3ea-4c23-41c6-a10f-5682bc08e3e1)

**Comment by bndkt** [comment]
Dark mode is my nemesis 🙈 Thank you for raising this, will look into it and fix it!

**Comment by bndkt** [comment]
This should be fixed with the latest release (1.0.6). Please let me know if you still see it.
