### ISSUE TITLE
On-premise mobile build (alternative to eas)

### ISSUE THREAD

**Issue by geoman2** [bndkt/sharemystack#265]
Hi, any plans to expand build process in order to run own server responsible with CI/CD for the mobile app build process?
Integration with coolify project would be ok, but there is no react native support yet, there is react native support in another repository https://github.com/filipeforattini/ff-iac-github-actions/blob/main/.github/workflows/mob.yml, but didn't try it myself. 
Maybe you give it a try?

**Comment by bndkt** [comment]
Thanks for the suggestion, but I'm pretty happy with the EAS setup and would rather focus my effort on additional features.
